version: "3.8"

services:
  marketplace-db:
    image: postgres:16-alpine
    restart: always
    container_name: marketplace-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - marketplace-db:/var/lib/postgresql/data

volumes:
  marketplace-db:
